// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRequestStoreInterfaceMock creates a new instance of RequestStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestStoreInterfaceMock {
	mock := &RequestStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RequestStoreInterfaceMock is an autogenerated mock type for the RequestStoreInterface type
type RequestStoreInterfaceMock struct {
	mock.Mock
}

type RequestStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestStoreInterfaceMock) EXPECT() *RequestStoreInterfaceMock_Expecter {
	return &RequestStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddRequest provides a mock function for the type RequestStoreInterfaceMock
func (_mock *RequestStoreInterfaceMock) AddRequest(ctx context.Context, value authRequestContext) (string, error) {
	ret := _mock.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for AddRequest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authRequestContext) (string, error)); ok {
		return returnFunc(ctx, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, authRequestContext) string); ok {
		r0 = returnFunc(ctx, value)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, authRequestContext) error); ok {
		r1 = returnFunc(ctx, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RequestStoreInterfaceMock_AddRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRequest'
type RequestStoreInterfaceMock_AddRequest_Call struct {
	*mock.Call
}

// AddRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - value authRequestContext
func (_e *RequestStoreInterfaceMock_Expecter) AddRequest(ctx interface{}, value interface{}) *RequestStoreInterfaceMock_AddRequest_Call {
	return &RequestStoreInterfaceMock_AddRequest_Call{Call: _e.mock.On("AddRequest", ctx, value)}
}

func (_c *RequestStoreInterfaceMock_AddRequest_Call) Run(run func(ctx context.Context, value authRequestContext)) *RequestStoreInterfaceMock_AddRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authRequestContext
		if args[1] != nil {
			arg1 = args[1].(authRequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RequestStoreInterfaceMock_AddRequest_Call) Return(s string, err error) *RequestStoreInterfaceMock_AddRequest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *RequestStoreInterfaceMock_AddRequest_Call) RunAndReturn(run func(ctx context.Context, value authRequestContext) (string, error)) *RequestStoreInterfaceMock_AddRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ClearRequest provides a mock function for the type RequestStoreInterfaceMock
func (_mock *RequestStoreInterfaceMock) ClearRequest(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ClearRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RequestStoreInterfaceMock_ClearRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRequest'
type RequestStoreInterfaceMock_ClearRequest_Call struct {
	*mock.Call
}

// ClearRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *RequestStoreInterfaceMock_Expecter) ClearRequest(ctx interface{}, key interface{}) *RequestStoreInterfaceMock_ClearRequest_Call {
	return &RequestStoreInterfaceMock_ClearRequest_Call{Call: _e.mock.On("ClearRequest", ctx, key)}
}

func (_c *RequestStoreInterfaceMock_ClearRequest_Call) Run(run func(ctx context.Context, key string)) *RequestStoreInterfaceMock_ClearRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RequestStoreInterfaceMock_ClearRequest_Call) Return(err error) *RequestStoreInterfaceMock_ClearRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RequestStoreInterfaceMock_ClearRequest_Call) RunAndReturn(run func(ctx context.Context, key string) error) *RequestStoreInterfaceMock_ClearRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function for the type RequestStoreInterfaceMock
func (_mock *RequestStoreInterfaceMock) GetRequest(ctx context.Context, key string) (bool, authRequestContext, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 bool
	var r1 authRequestContext
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, authRequestContext, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) authRequestContext); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(authRequestContext)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RequestStoreInterfaceMock_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type RequestStoreInterfaceMock_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *RequestStoreInterfaceMock_Expecter) GetRequest(ctx interface{}, key interface{}) *RequestStoreInterfaceMock_GetRequest_Call {
	return &RequestStoreInterfaceMock_GetRequest_Call{Call: _e.mock.On("GetRequest", ctx, key)}
}

func (_c *RequestStoreInterfaceMock_GetRequest_Call) Run(run func(ctx context.Context, key string)) *RequestStoreInterfaceMock_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RequestStoreInterfaceMock_GetRequest_Call) Return(b bool, authRequestContextMoqParam authRequestContext, err error) *RequestStoreInterfaceMock_GetRequest_Call {
	_c.Call.Return(b, authRequestContextMoqParam, err)
	return _c
}

func (_c *RequestStoreInterfaceMock_GetRequest_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, authRequestContext, error)) *RequestStoreInterfaceMock_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}
