// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package par

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewStoreInterfaceMock creates a new instance of StoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreInterfaceMock {
	mock := &StoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StoreInterfaceMock is an autogenerated mock type for the StoreInterface type
type StoreInterfaceMock struct {
	mock.Mock
}

type StoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreInterfaceMock) EXPECT() *StoreInterfaceMock_Expecter {
	return &StoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type StoreInterfaceMock
func (_mock *StoreInterfaceMock) Consume(ctx context.Context, randomKey string) (pushedAuthorizationRequest, bool, error) {
	ret := _mock.Called(ctx, randomKey)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 pushedAuthorizationRequest
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (pushedAuthorizationRequest, bool, error)); ok {
		return returnFunc(ctx, randomKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) pushedAuthorizationRequest); ok {
		r0 = returnFunc(ctx, randomKey)
	} else {
		r0 = ret.Get(0).(pushedAuthorizationRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, randomKey)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, randomKey)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// StoreInterfaceMock_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type StoreInterfaceMock_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - randomKey string
func (_e *StoreInterfaceMock_Expecter) Consume(ctx interface{}, randomKey interface{}) *StoreInterfaceMock_Consume_Call {
	return &StoreInterfaceMock_Consume_Call{Call: _e.mock.On("Consume", ctx, randomKey)}
}

func (_c *StoreInterfaceMock_Consume_Call) Run(run func(ctx context.Context, randomKey string)) *StoreInterfaceMock_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreInterfaceMock_Consume_Call) Return(pushedAuthorizationRequestMoqParam pushedAuthorizationRequest, b bool, err error) *StoreInterfaceMock_Consume_Call {
	_c.Call.Return(pushedAuthorizationRequestMoqParam, b, err)
	return _c
}

func (_c *StoreInterfaceMock_Consume_Call) RunAndReturn(run func(ctx context.Context, randomKey string) (pushedAuthorizationRequest, bool, error)) *StoreInterfaceMock_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type StoreInterfaceMock
func (_mock *StoreInterfaceMock) Store(ctx context.Context, request pushedAuthorizationRequest, expirySeconds int64) (string, error) {
	ret := _mock.Called(ctx, request, expirySeconds)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pushedAuthorizationRequest, int64) (string, error)); ok {
		return returnFunc(ctx, request, expirySeconds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pushedAuthorizationRequest, int64) string); ok {
		r0 = returnFunc(ctx, request, expirySeconds)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pushedAuthorizationRequest, int64) error); ok {
		r1 = returnFunc(ctx, request, expirySeconds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreInterfaceMock_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type StoreInterfaceMock_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - request pushedAuthorizationRequest
//   - expirySeconds int64
func (_e *StoreInterfaceMock_Expecter) Store(ctx interface{}, request interface{}, expirySeconds interface{}) *StoreInterfaceMock_Store_Call {
	return &StoreInterfaceMock_Store_Call{Call: _e.mock.On("Store", ctx, request, expirySeconds)}
}

func (_c *StoreInterfaceMock_Store_Call) Run(run func(ctx context.Context, request pushedAuthorizationRequest, expirySeconds int64)) *StoreInterfaceMock_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pushedAuthorizationRequest
		if args[1] != nil {
			arg1 = args[1].(pushedAuthorizationRequest)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StoreInterfaceMock_Store_Call) Return(s string, err error) *StoreInterfaceMock_Store_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *StoreInterfaceMock_Store_Call) RunAndReturn(run func(ctx context.Context, request pushedAuthorizationRequest, expirySeconds int64) (string, error)) *StoreInterfaceMock_Store_Call {
	_c.Call.Return(run)
	return _c
}
