// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmgtmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/flow/mgt"
)

// NewHostFlowDefinitionProviderMock creates a new instance of HostFlowDefinitionProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHostFlowDefinitionProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HostFlowDefinitionProviderMock {
	mock := &HostFlowDefinitionProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HostFlowDefinitionProviderMock is an autogenerated mock type for the HostFlowDefinitionProvider type
type HostFlowDefinitionProviderMock struct {
	mock.Mock
}

type HostFlowDefinitionProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HostFlowDefinitionProviderMock) EXPECT() *HostFlowDefinitionProviderMock_Expecter {
	return &HostFlowDefinitionProviderMock_Expecter{mock: &_m.Mock}
}

// GetFlowByHandle provides a mock function for the type HostFlowDefinitionProviderMock
func (_mock *HostFlowDefinitionProviderMock) GetFlowByHandle(ctx context.Context, appID string, handle string) (*flowmgt.HostFlowDefinition, error) {
	ret := _mock.Called(ctx, appID, handle)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowByHandle")
	}

	var r0 *flowmgt.HostFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*flowmgt.HostFlowDefinition, error)); ok {
		return returnFunc(ctx, appID, handle)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *flowmgt.HostFlowDefinition); ok {
		r0 = returnFunc(ctx, appID, handle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.HostFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, handle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HostFlowDefinitionProviderMock_GetFlowByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowByHandle'
type HostFlowDefinitionProviderMock_GetFlowByHandle_Call struct {
	*mock.Call
}

// GetFlowByHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - handle string
func (_e *HostFlowDefinitionProviderMock_Expecter) GetFlowByHandle(ctx interface{}, appID interface{}, handle interface{}) *HostFlowDefinitionProviderMock_GetFlowByHandle_Call {
	return &HostFlowDefinitionProviderMock_GetFlowByHandle_Call{Call: _e.mock.On("GetFlowByHandle", ctx, appID, handle)}
}

func (_c *HostFlowDefinitionProviderMock_GetFlowByHandle_Call) Run(run func(ctx context.Context, appID string, handle string)) *HostFlowDefinitionProviderMock_GetFlowByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HostFlowDefinitionProviderMock_GetFlowByHandle_Call) Return(hostFlowDefinition *flowmgt.HostFlowDefinition, err error) *HostFlowDefinitionProviderMock_GetFlowByHandle_Call {
	_c.Call.Return(hostFlowDefinition, err)
	return _c
}

func (_c *HostFlowDefinitionProviderMock_GetFlowByHandle_Call) RunAndReturn(run func(ctx context.Context, appID string, handle string) (*flowmgt.HostFlowDefinition, error)) *HostFlowDefinitionProviderMock_GetFlowByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowByID provides a mock function for the type HostFlowDefinitionProviderMock
func (_mock *HostFlowDefinitionProviderMock) GetFlowByID(ctx context.Context, id string) (*flowmgt.HostFlowDefinition, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowByID")
	}

	var r0 *flowmgt.HostFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*flowmgt.HostFlowDefinition, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *flowmgt.HostFlowDefinition); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.HostFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HostFlowDefinitionProviderMock_GetFlowByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowByID'
type HostFlowDefinitionProviderMock_GetFlowByID_Call struct {
	*mock.Call
}

// GetFlowByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *HostFlowDefinitionProviderMock_Expecter) GetFlowByID(ctx interface{}, id interface{}) *HostFlowDefinitionProviderMock_GetFlowByID_Call {
	return &HostFlowDefinitionProviderMock_GetFlowByID_Call{Call: _e.mock.On("GetFlowByID", ctx, id)}
}

func (_c *HostFlowDefinitionProviderMock_GetFlowByID_Call) Run(run func(ctx context.Context, id string)) *HostFlowDefinitionProviderMock_GetFlowByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HostFlowDefinitionProviderMock_GetFlowByID_Call) Return(hostFlowDefinition *flowmgt.HostFlowDefinition, err error) *HostFlowDefinitionProviderMock_GetFlowByID_Call {
	_c.Call.Return(hostFlowDefinition, err)
	return _c
}

func (_c *HostFlowDefinitionProviderMock_GetFlowByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*flowmgt.HostFlowDefinition, error)) *HostFlowDefinitionProviderMock_GetFlowByID_Call {
	_c.Call.Return(run)
	return _c
}
