// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cryptomock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine"
)

// NewRuntimeCryptoProviderMock creates a new instance of RuntimeCryptoProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuntimeCryptoProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuntimeCryptoProviderMock {
	mock := &RuntimeCryptoProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RuntimeCryptoProviderMock is an autogenerated mock type for the RuntimeCryptoProvider type
type RuntimeCryptoProviderMock struct {
	mock.Mock
}

type RuntimeCryptoProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RuntimeCryptoProviderMock) EXPECT() *RuntimeCryptoProviderMock_Expecter {
	return &RuntimeCryptoProviderMock_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type RuntimeCryptoProviderMock
func (_mock *RuntimeCryptoProviderMock) Decrypt(ctx context.Context, keyRef *thunderidengine.KeyRef, params thunderidengine.AlgorithmParams, content []byte) ([]byte, error) {
	ret := _mock.Called(ctx, keyRef, params, content)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *thunderidengine.KeyRef, thunderidengine.AlgorithmParams, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, keyRef, params, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *thunderidengine.KeyRef, thunderidengine.AlgorithmParams, []byte) []byte); ok {
		r0 = returnFunc(ctx, keyRef, params, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *thunderidengine.KeyRef, thunderidengine.AlgorithmParams, []byte) error); ok {
		r1 = returnFunc(ctx, keyRef, params, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuntimeCryptoProviderMock_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type RuntimeCryptoProviderMock_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - keyRef *thunderidengine.KeyRef
//   - params thunderidengine.AlgorithmParams
//   - content []byte
func (_e *RuntimeCryptoProviderMock_Expecter) Decrypt(ctx interface{}, keyRef interface{}, params interface{}, content interface{}) *RuntimeCryptoProviderMock_Decrypt_Call {
	return &RuntimeCryptoProviderMock_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, keyRef, params, content)}
}

func (_c *RuntimeCryptoProviderMock_Decrypt_Call) Run(run func(ctx context.Context, keyRef *thunderidengine.KeyRef, params thunderidengine.AlgorithmParams, content []byte)) *RuntimeCryptoProviderMock_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *thunderidengine.KeyRef
		if args[1] != nil {
			arg1 = args[1].(*thunderidengine.KeyRef)
		}
		var arg2 thunderidengine.AlgorithmParams
		if args[2] != nil {
			arg2 = args[2].(thunderidengine.AlgorithmParams)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RuntimeCryptoProviderMock_Decrypt_Call) Return(bytes []byte, err error) *RuntimeCryptoProviderMock_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *RuntimeCryptoProviderMock_Decrypt_Call) RunAndReturn(run func(ctx context.Context, keyRef *thunderidengine.KeyRef, params thunderidengine.AlgorithmParams, content []byte) ([]byte, error)) *RuntimeCryptoProviderMock_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type RuntimeCryptoProviderMock
func (_mock *RuntimeCryptoProviderMock) Encrypt(ctx context.Context, keyRef *thunderidengine.KeyRef, params thunderidengine.AlgorithmParams, content []byte) ([]byte, error) {
	ret := _mock.Called(ctx, keyRef, params, content)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *thunderidengine.KeyRef, thunderidengine.AlgorithmParams, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, keyRef, params, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *thunderidengine.KeyRef, thunderidengine.AlgorithmParams, []byte) []byte); ok {
		r0 = returnFunc(ctx, keyRef, params, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *thunderidengine.KeyRef, thunderidengine.AlgorithmParams, []byte) error); ok {
		r1 = returnFunc(ctx, keyRef, params, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuntimeCryptoProviderMock_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type RuntimeCryptoProviderMock_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - keyRef *thunderidengine.KeyRef
//   - params thunderidengine.AlgorithmParams
//   - content []byte
func (_e *RuntimeCryptoProviderMock_Expecter) Encrypt(ctx interface{}, keyRef interface{}, params interface{}, content interface{}) *RuntimeCryptoProviderMock_Encrypt_Call {
	return &RuntimeCryptoProviderMock_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, keyRef, params, content)}
}

func (_c *RuntimeCryptoProviderMock_Encrypt_Call) Run(run func(ctx context.Context, keyRef *thunderidengine.KeyRef, params thunderidengine.AlgorithmParams, content []byte)) *RuntimeCryptoProviderMock_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *thunderidengine.KeyRef
		if args[1] != nil {
			arg1 = args[1].(*thunderidengine.KeyRef)
		}
		var arg2 thunderidengine.AlgorithmParams
		if args[2] != nil {
			arg2 = args[2].(thunderidengine.AlgorithmParams)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RuntimeCryptoProviderMock_Encrypt_Call) Return(bytes []byte, err error) *RuntimeCryptoProviderMock_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *RuntimeCryptoProviderMock_Encrypt_Call) RunAndReturn(run func(ctx context.Context, keyRef *thunderidengine.KeyRef, params thunderidengine.AlgorithmParams, content []byte) ([]byte, error)) *RuntimeCryptoProviderMock_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicKeys provides a mock function for the type RuntimeCryptoProviderMock
func (_mock *RuntimeCryptoProviderMock) GetPublicKeys(ctx context.Context, filter thunderidengine.PublicKeyFilter) ([]thunderidengine.PublicKeyInfo, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKeys")
	}

	var r0 []thunderidengine.PublicKeyInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, thunderidengine.PublicKeyFilter) ([]thunderidengine.PublicKeyInfo, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, thunderidengine.PublicKeyFilter) []thunderidengine.PublicKeyInfo); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]thunderidengine.PublicKeyInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, thunderidengine.PublicKeyFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuntimeCryptoProviderMock_GetPublicKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKeys'
type RuntimeCryptoProviderMock_GetPublicKeys_Call struct {
	*mock.Call
}

// GetPublicKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - filter thunderidengine.PublicKeyFilter
func (_e *RuntimeCryptoProviderMock_Expecter) GetPublicKeys(ctx interface{}, filter interface{}) *RuntimeCryptoProviderMock_GetPublicKeys_Call {
	return &RuntimeCryptoProviderMock_GetPublicKeys_Call{Call: _e.mock.On("GetPublicKeys", ctx, filter)}
}

func (_c *RuntimeCryptoProviderMock_GetPublicKeys_Call) Run(run func(ctx context.Context, filter thunderidengine.PublicKeyFilter)) *RuntimeCryptoProviderMock_GetPublicKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 thunderidengine.PublicKeyFilter
		if args[1] != nil {
			arg1 = args[1].(thunderidengine.PublicKeyFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuntimeCryptoProviderMock_GetPublicKeys_Call) Return(publicKeyInfos []thunderidengine.PublicKeyInfo, err error) *RuntimeCryptoProviderMock_GetPublicKeys_Call {
	_c.Call.Return(publicKeyInfos, err)
	return _c
}

func (_c *RuntimeCryptoProviderMock_GetPublicKeys_Call) RunAndReturn(run func(ctx context.Context, filter thunderidengine.PublicKeyFilter) ([]thunderidengine.PublicKeyInfo, error)) *RuntimeCryptoProviderMock_GetPublicKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetTLSMaterial provides a mock function for the type RuntimeCryptoProviderMock
func (_mock *RuntimeCryptoProviderMock) GetTLSMaterial(ctx context.Context, keyRef *thunderidengine.KeyRef) (*thunderidengine.TLSMaterial, error) {
	ret := _mock.Called(ctx, keyRef)

	if len(ret) == 0 {
		panic("no return value specified for GetTLSMaterial")
	}

	var r0 *thunderidengine.TLSMaterial
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *thunderidengine.KeyRef) (*thunderidengine.TLSMaterial, error)); ok {
		return returnFunc(ctx, keyRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *thunderidengine.KeyRef) *thunderidengine.TLSMaterial); ok {
		r0 = returnFunc(ctx, keyRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*thunderidengine.TLSMaterial)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *thunderidengine.KeyRef) error); ok {
		r1 = returnFunc(ctx, keyRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuntimeCryptoProviderMock_GetTLSMaterial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTLSMaterial'
type RuntimeCryptoProviderMock_GetTLSMaterial_Call struct {
	*mock.Call
}

// GetTLSMaterial is a helper method to define mock.On call
//   - ctx context.Context
//   - keyRef *thunderidengine.KeyRef
func (_e *RuntimeCryptoProviderMock_Expecter) GetTLSMaterial(ctx interface{}, keyRef interface{}) *RuntimeCryptoProviderMock_GetTLSMaterial_Call {
	return &RuntimeCryptoProviderMock_GetTLSMaterial_Call{Call: _e.mock.On("GetTLSMaterial", ctx, keyRef)}
}

func (_c *RuntimeCryptoProviderMock_GetTLSMaterial_Call) Run(run func(ctx context.Context, keyRef *thunderidengine.KeyRef)) *RuntimeCryptoProviderMock_GetTLSMaterial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *thunderidengine.KeyRef
		if args[1] != nil {
			arg1 = args[1].(*thunderidengine.KeyRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuntimeCryptoProviderMock_GetTLSMaterial_Call) Return(tLSMaterial *thunderidengine.TLSMaterial, err error) *RuntimeCryptoProviderMock_GetTLSMaterial_Call {
	_c.Call.Return(tLSMaterial, err)
	return _c
}

func (_c *RuntimeCryptoProviderMock_GetTLSMaterial_Call) RunAndReturn(run func(ctx context.Context, keyRef *thunderidengine.KeyRef) (*thunderidengine.TLSMaterial, error)) *RuntimeCryptoProviderMock_GetTLSMaterial_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type RuntimeCryptoProviderMock
func (_mock *RuntimeCryptoProviderMock) Sign(ctx context.Context, keyRef thunderidengine.KeyRef, algorithm thunderidengine.SignAlgorithm, content []byte) ([]byte, error) {
	ret := _mock.Called(ctx, keyRef, algorithm, content)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, thunderidengine.KeyRef, thunderidengine.SignAlgorithm, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, keyRef, algorithm, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, thunderidengine.KeyRef, thunderidengine.SignAlgorithm, []byte) []byte); ok {
		r0 = returnFunc(ctx, keyRef, algorithm, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, thunderidengine.KeyRef, thunderidengine.SignAlgorithm, []byte) error); ok {
		r1 = returnFunc(ctx, keyRef, algorithm, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuntimeCryptoProviderMock_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type RuntimeCryptoProviderMock_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - keyRef thunderidengine.KeyRef
//   - algorithm thunderidengine.SignAlgorithm
//   - content []byte
func (_e *RuntimeCryptoProviderMock_Expecter) Sign(ctx interface{}, keyRef interface{}, algorithm interface{}, content interface{}) *RuntimeCryptoProviderMock_Sign_Call {
	return &RuntimeCryptoProviderMock_Sign_Call{Call: _e.mock.On("Sign", ctx, keyRef, algorithm, content)}
}

func (_c *RuntimeCryptoProviderMock_Sign_Call) Run(run func(ctx context.Context, keyRef thunderidengine.KeyRef, algorithm thunderidengine.SignAlgorithm, content []byte)) *RuntimeCryptoProviderMock_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 thunderidengine.KeyRef
		if args[1] != nil {
			arg1 = args[1].(thunderidengine.KeyRef)
		}
		var arg2 thunderidengine.SignAlgorithm
		if args[2] != nil {
			arg2 = args[2].(thunderidengine.SignAlgorithm)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RuntimeCryptoProviderMock_Sign_Call) Return(bytes []byte, err error) *RuntimeCryptoProviderMock_Sign_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *RuntimeCryptoProviderMock_Sign_Call) RunAndReturn(run func(ctx context.Context, keyRef thunderidengine.KeyRef, algorithm thunderidengine.SignAlgorithm, content []byte) ([]byte, error)) *RuntimeCryptoProviderMock_Sign_Call {
	_c.Call.Return(run)
	return _c
}
